Added RoomController
ronaldvandijk/colloquiumapp pull request #16
Opened 2016-11-09 14:18 UTC by Darkwater

2016-11-09 14:36 UTC, Darkwater commented
After the merge from master, /admin/rooms shows a white screen?? idk there's something fishy goin on here. **Don't merge yet**

2016-11-10 10:16 UTC, Darkwater commented
Fixed by f91522d, ready to merge.

2016-11-10 10:17 UTC, mro95 requested changes

2016-11-10 10:17 UTC, mro95 commented on app/Http/Controllers/Admin/RoomController.php
> +    {
Need validation. Example:
```
$this->validate($request,[
    'name' => 'required|unique:locations',
    'city_id' => 'required|numberic',
]);
```

https://laravel.com/docs/5.3/validation

2016-11-10 10:17 UTC, mro95 commented on app/Http/Controllers/Admin/RoomController.php
> +        Room::create([
Betere manier
```
        $location = new Location();
        $location->name = $request->input('name');
        $location->city_id = $request->input('city_id');
        $location->save();
```

2016-11-10 10:17 UTC, mro95 commented on app/Http/Controllers/Admin/RoomController.php
> +        return redirect('/admin/rooms');
Give user feedback about successfully saved. This is what i did.
```
$request->session()->flash('success', 'The new location "'.$location->name.'" is successfully saved!');
```

2016-11-10 10:17 UTC, mro95 commented on app/Http/Controllers/SearchController.php
>              $colloquiums = DB::select('select colloquia.*, rooms.name from colloquia , rooms where colloquia.room_id = rooms.id AND DATE(colloquia.start_date) = ?', [$date]);
Eeeeh??

2016-11-10 10:17 UTC, mro95 commented on resources/views/admin/rooms/overview.blade.php
> +        <div class="row">
Hier ergens moet je dan ergens die success error laten zien

2016-11-10 10:17 UTC, mro95 commented on resources/views/admin/rooms/create.blade.php
> +        <div class="row">
en hier moet je dan over $errors lopen voor de validatie

2016-11-10 11:19 UTC, sandervankasteel commented
Please fix merge conflict

2016-11-10 11:38 UTC, Darkwater commented
Added validation, cc @mro95 and @sandervankasteel

2016-11-10 11:58 UTC, mro95 approved these changes

2016-11-10 13:31 UTC, mro95 commented on app/Http/Controllers/Admin/RoomController.php
> +        $this->middleware('auth');
Dit moet weg. Is besproken met groep

2016-11-10 15:11 UTC, sandervankasteel commented
Fix merge conflicts first!

2016-11-10 15:13 UTC, Darkwater commented
It was fine when I merged :<

2016-11-10 17:46 UTC, maantje commented
Aangezien er niemand meer is en wij verder willen wordt deze geclosed en opnieuw opgepakt

2016-11-10 17:46 UTC, closed without merging