Buildings
ronaldvandijk/colloquiumapp pull request #32
Opened 2016-11-10 13:45 UTC by Prolael

2016-11-10 17:23 UTC, maantje requested changes

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +        $this->middleware('auth');
Constructor can eruit middelware aangeven in je route

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +        return view('admin.buildings.list', ['buildings' => Building::all()]);
Buildings moet building worden View folders enkel voud.

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +        return view('admin.buildings.create', ['locations' =>  Location::all()]);
Buildings moet building worden View folders enkel voud.

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +        $this->validate($request, [
Hier voor FormRequest gebruiken https://laravel.com/docs/5.3/validation#form-request-validation

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +        $building = new Building();
Building wordt nooit opgeslagen en je kan beter Build::create($request->all()) doen.

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +        try {
Try catch is nergens voor nodig aangezien je findOrFail gebruikt

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +        try {
Hier geld hetzelfde try catch is nutteloos

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +            $this->validate($request, [
Hier ook weer Form Request voor gebruiken

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +            $building->save();
Building::create($request->all()); gebruiken

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +            return redirect()->action('Admin\BuildingController@index');
Mist een flash message terug als feedback

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +        try {
Try catch is hier ook nutteloos

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/create.blade.php
> +                        <form action="/admin/building" method="POST">
Url helper gebruiken voor je action

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/edit.blade.php
> +                        <form action="/admin/building/{{ $building->id }}" method="POST">
Hier ook url helper gebruiken

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                            <a href="/admin/building/create" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i>Gebouw toevoegen</a>
Hier ook weer url helper gebruiken

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                                    <td><a href="/admin/building/{{$building->id}}/edit" class="btn btn-primary"><i class="fa fa-pencil" aria-hidden="true"></i> Bewerken</a></td>
en hier ook

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                                        <form method="post" action="/admin/building/{{$building->id}}">
en daar

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                        <b>Gebouwen</b>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                            <a href="/admin/building/create" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i>Gebouw toevoegen</a>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                                <th>Naam</th>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                                <th>Gebouw</th>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                                <th>Stad</th>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                                <th>Afkorting</th>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                                <th>Bewerken</th>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                                <th>Verwijderen</th>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                                <tr style="margin-top: 50px; margin-bottom: 5em;">
Inline css??????

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                                    <td><a href="/admin/building/{{$building->id}}/edit" class="btn btn-primary"><i class="fa fa-pencil" aria-hidden="true"></i> Bewerken</a></td>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +                'name' => 'required|unique:buildings,id,'.$building->id,
psr2 gebruiken moet een spatie bij  ' ' . ' ';

2016-11-10 17:23 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +                'abbreviation' => 'required|unique:buildings,abbreviation,'.$building->abbreviation,
zelfde als hierboven

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/create.blade.php
> +                        <b>Gebouw toevoegen</b>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/create.blade.php
> +                            <label>Naam: </label><input name="name" />
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/create.blade.php
> +                            <label>locatie: </label>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/create.blade.php
> +                            <label>Abbreviation: </label><input type="text" name="abbreviation">
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/edit.blade.php
> +                        <b>Gebouw toevoegen</b>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/edit.blade.php
> +                            <label>Naam: </label><input name="name" value="{{ $building->name }}" />
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/edit.blade.php
> +                            <label>locatie: </label>
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/edit.blade.php
> +                            <label>Abbreviation: </label><input type="text" name="abbreviation" value="{{ $building->abbreviation }}">
Geen translation gebruikt

2016-11-10 17:23 UTC, maantje commented on resources/views/admin/buildings/list.blade.php
> +                                    <td><a href="/admin/building/{{$building->id}}/edit" class="btn btn-primary"><i class="fa fa-pencil" aria-hidden="true"></i> Bewerken</a></td>
url helper gebruiken

2016-11-14 11:17 UTC, sandervankasteel commented
@Prolael please fix your merge conflict. After that it can be merged

2016-11-14 11:19 UTC, Prolael commented
Done now,  will be pushed together with the documentation.

2016-11-14 12:12 UTC, maantje requested changes

2016-11-14 12:12 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +                $request->session()->flash('uniqueError', 'There already exists a combination with this name and abbreviation.');
Geen translation.

2016-11-14 12:12 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +        throw new NotFoundHttpException();
geen show method?

2016-11-14 12:12 UTC, maantje commented on app/Http/Controllers/Admin/BuildingController.php
> +                $request->session()->flash('error', 'The combination of name and abbreviation was no unique.');
translation

2016-11-14 12:12 UTC, maantje commented on app/Http/Requests/BuildingRequest.php
> +    public function rules()
geen rules?

2016-11-14 12:13 UTC, Prolael commented on app/Http/Controllers/Admin/BuildingController.php
> +        throw new NotFoundHttpException();
we hebben geen show voor individuele buildings.

2016-11-14 12:27 UTC, Prolael commented on app/Http/Requests/BuildingRequest.php
> +    public function rules()
dit is helaas nog over van de kwestie "De combinatie van de Afkorting+gebouwnaam moet uniek zijn". Niet zo netjes van mij om dit niet te ontcommenten.

2016-11-14 15:21 UTC, merged